'use strict';
const {test,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createServer}=require('../server/server.cjs');
const N=require('../web/network.js');
let server,base;
async function start(dbPath=':memory:'){server=createServer({dbPath});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;}
async function stop(){server.closeAllConnections();await new Promise(r=>server.close(r));}
beforeEach(()=>start());afterEach(()=>stop());
const valid=()=>({kind:'found',category:'校园卡',title:'蓝色校园卡',place:'图书馆一楼',description:'卡套贴有星星',contact:'图书馆服务台',occurredAt:'2026-01-01T12:00:00+08:00',requestKey:require('node:crypto').randomUUID()});
async function call(route,method='GET',input,token){const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(input!==undefined?{body:typeof input==='string'?input:JSON.stringify(input)}:{})});return {status:r.status,body:await r.json()};}
async function session(){return (await call('/api/sessions','POST',{})).body;}
async function publish(s,input=valid()){return call('/api/items','POST',input,s.token);}
test('健康接口和空公共列表可匿名读取',async()=>{assert.equal((await call('/api/health')).body.ok,true);assert.deepEqual((await call('/api/items')).body.items,[]);});
test('两台客户端得到不同的发布者凭证',async()=>{const a=await session(),b=await session();assert.notEqual(a.ownerId,b.ownerId);assert.notEqual(a.token,b.token);assert.match(a.token,/^[a-f0-9]{64}$/);});
test('服务根据凭证返回自己的身份',async()=>{const a=await session();assert.equal((await call('/api/me','GET',undefined,a.token)).body.ownerId,a.ownerId);});
test('没有凭证和伪造凭证都不能发布',async()=>{assert.equal((await publish({token:''})).status,401);assert.equal((await publish({token:'a'.repeat(64)})).status,401);});
test('甲发布的信息立即出现在公共列表和详情',async()=>{const a=await session(),{body,status}=await publish(a);assert.equal(status,201);const item=body.item;assert.equal(item.ownerId,a.ownerId);assert.equal((await call('/api/items')).body.items[0].id,item.id);assert.deepEqual((await call('/api/items/'+item.id)).body.item,item);});
test('客户端传入别人 ownerId 或 resolved 被服务忽略',async()=>{const a=await session(),{body}=await publish(a,{...valid(),ownerId:'other',status:'resolved'});assert.equal(body.item.ownerId,a.ownerId);assert.equal(body.item.status,'open');});
test('中文 UTF8 被网络分段后仍保持完整',async()=>{const a=await session(),input=valid(),bytes=Buffer.from(JSON.stringify(input));const first=bytes.indexOf(Buffer.from('蓝'))+1;const result=await new Promise((resolve,reject)=>{const req=require('node:http').request(base+'/api/items',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+a.token}},res=>{let text='';res.setEncoding('utf8');res.on('data',x=>text+=x);res.on('end',()=>resolve(JSON.parse(text)));});req.on('error',reject);req.write(bytes.subarray(0,first));setTimeout(()=>req.end(bytes.subarray(first)),10);});assert.equal(result.item.title,input.title);});
test('空文本、未来时间和非法类别分别返回校验错误',async()=>{const a=await session();for(const change of [{title:' '},{occurredAt:'2099-01-01'},{category:'不支持'}]){const r=await publish(a,{...valid(),...change});assert.equal(r.status,400);assert.ok(r.body.errors);}});
test('超长文本不能通过直接调用接口绕过表单',async()=>{assert.equal((await publish(await session(),{...valid(),title:'字'.repeat(41)})).status,400);});
test('跨时区按同一时刻校验并拒绝缺少时区的API时间',async()=>{const a=await session();assert.equal((await publish(a,{...valid(),occurredAt:'2026-01-01T12:00:00+08:00'})).status,201);assert.equal((await publish(a,{...valid(),occurredAt:'2026-01-01T12:00'})).status,400);});
test('同一发布请求重试只生成一条信息',async()=>{const a=await session(),input=valid(),first=await publish(a,input),again=await publish(a,input);assert.equal(again.status,200);assert.equal(again.body.item.id,first.body.item.id);assert.equal((await call('/api/items')).body.items.length,1);});
test('同一请求号改内容返回冲突而非覆盖',async()=>{const a=await session(),input=valid();await publish(a,input);assert.equal((await publish(a,{...input,title:'改变标题'})).status,409);});
test('不同发布者使用相同请求号仍独立保存',async()=>{const input=valid();await publish(await session(),input);await publish(await session(),input);assert.equal((await call('/api/items')).body.items.length,2);});
test('并发发布不丢失另一条记录',async()=>{const a=await session(),b=await session();const results=await Promise.all([publish(a),publish(b)]);assert.ok(results.every(x=>x.status===201));assert.equal((await call('/api/items')).body.items.length,2);});
test('乙即使知道甲的信息编号也不能更新状态',async()=>{const a=await session(),b=await session(),{body}=await publish(a);const r=await call('/api/items/'+body.item.id+'/status','PATCH',{status:'resolved',ownerId:a.ownerId},b.token);assert.equal(r.status,403);assert.equal((await call('/api/items/'+body.item.id)).body.item.status,'open');});
test('匿名状态更新被拒绝',async()=>{const {body}=await publish(await session());assert.equal((await call('/api/items/'+body.item.id+'/status','PATCH',{status:'resolved'})).status,401);});
test('甲确认归还后乙读取到最新状态，可恢复进行中',async()=>{const a=await session(),{body}=await publish(a),route='/api/items/'+body.item.id;assert.equal((await call(route+'/status','PATCH',{status:'resolved'},a.token)).status,200);assert.equal((await call('/api/items')).body.items[0].status,'resolved');assert.equal((await call(route+'/status','PATCH',{status:'open'},a.token)).body.item.status,'open');});
test('非法状态不会更改数据',async()=>{const a=await session(),{body}=await publish(a);assert.equal((await call('/api/items/'+body.item.id+'/status','PATCH',{status:'deleted'},a.token)).status,400);assert.equal((await call('/api/items')).body.items[0].status,'open');});
test('服务支持关键词、类别、地点、类型和状态组合搜索',async()=>{const a=await session();await publish(a);await publish(a,{...valid(),title:'黑色雨伞',category:'雨伞',place:'食堂'});const url='/api/items?'+new URLSearchParams({q:'校园卡',category:'校园卡',place:'图书馆',kind:'found',status:'open'});assert.equal((await call(url)).body.items.length,1);assert.equal((await call('/api/items?q=无结果')).body.items.length,0);});
test('公共响应不包含凭证或其哈希',async()=>{const a=await session();await publish(a);const raw=JSON.stringify((await call('/api/items')).body);assert.ok(!raw.includes(a.token));assert.ok(!raw.includes('token_hash'));});
test('畸形JSON、数组、过长请求、不存在接口和记录均可处理',async()=>{const a=await session();assert.equal((await call('/api/items','POST','{',a.token)).status,400);assert.equal((await call('/api/items','POST',[],a.token)).status,400);assert.equal((await call('/api/items','POST',{extra:'x'.repeat(20000)},a.token)).status,413);assert.equal((await call('/api/unknown')).status,404);assert.equal((await call('/api/items/00000000-0000-0000-0000-000000000000')).status,404);});
test('重启服务后 SQLite 信息和原发布者凭证都保留',async()=>{await stop();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiguang-'));try{const db=path.join(dir,'test.sqlite');await start(db);const a=await session(),{body}=await publish(a);await stop();await start(db);assert.equal((await call('/api/items')).body.items[0].id,body.item.id);assert.equal((await call('/api/me','GET',undefined,a.token)).body.ownerId,a.ownerId);}finally{await stop();fs.rmSync(dir,{recursive:true,force:true});await start();}});
test('服务地址归一化并限制 HTTP 到局域网',()=>{assert.equal(N.normalizeBase('http://192.168.1.2:8787/'),'http://192.168.1.2:8787');assert.equal(N.normalizeBase('https://campus.example.com'),'https://campus.example.com');for(const value of ['http://example.com','https://user:password@example.com','https://example.com/a','https://example.com/?key=123','file:///a'])assert.throws(()=>N.normalizeBase(value));});
test('联网模块传播服务失败而不构造发布成功',async()=>{await assert.rejects(N.request(base,'/api/items','POST',valid()),/凭证/);const a=await session();assert.equal((await N.request(base,'/api/items','POST',valid(),a.token)).item.ownerId,a.ownerId);});
